version: '2.2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
      PHP_CS_FIXER_ALLOW_XDEBUG: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8003:80'

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: register-bd
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-problem
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80




volumes:
  db: { }