version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8003:80'

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '33062:3306'

volumes:
  db: { }